export const SUBCATEGORIES_LIST_REQUEST = 'SUBCATEGORIES_LIST_REQUEST'
export const SUBCATEGORIES_LIST_SUCCESS = 'SUBCATEGORIES_LIST_SUCCESS'
export const SUBCATEGORIES_LIST_FAIL = 'SUBCATEGORIES_LIST_FAIL'

export const SUBCATEGORIES_LIST_BY_CATEGORY_REQUEST = 'SUBCATEGORIES_LIST_OF_CATEGORY_REQUEST'
export const SUBCATEGORIES_LIST_BY_CATEGORY_SUCCESS = 'SUBCATEGORIES_LIST_OF_CATEGORY_SUCCESS'
export const SUBCATEGORIES_LIST_BY_CATEGORY_FAIL = 'SUBCATEGORIES_LIST_OF_CATEGORY_FAIL'
