export const CATEGORIES_LIST_REQUEST = 'CATEGORIES_LIST_REQUEST'
export const CATEGORIES_LIST_SUCCESS = 'CATEGORIES_LIST_SUCCESS'
export const CATEGORIES_LIST_FAIL = 'CATEGORIES_LIST_FAIL'

export const CATEGORIES_CREATE_REQUEST = 'CATEGORIES_CREATE_REQUEST'
export const CATEGORIES_CREATE_SUCCESS = 'CATEGORIES_CREATE_SUCCESS'
export const CATEGORIES_CREATE_FAIL = 'CATEGORIES_CREATE_FAIL'